<?php
namespace Aurora\Enterprise\CLI;

use WP_CLI_Command;
use WP_CLI;
use wpdb;

use function current_time;
use function gmdate;
use function max;
use function microtime;
use function sanitize_title;
use function sprintf;
use function strtoupper;
use function uniqid;

class Product_Seed_Command extends WP_CLI_Command {
    private wpdb $db;

    public function __construct() {
        global $wpdb;
        $this->db = $wpdb;
    }

    /**
     * Seed a large batch of WooCommerce products using high-throughput direct SQL.
     *
     * ## OPTIONS
     *
     * [--count=<number>]
     * : Number of products to create. Default: 50000.
     *
     * [--start-index=<number>]
     * : Optional manual starting counter (overrides auto-detection).
     *
     * [--progress=<number>]
     * : Log progress every N products. Default: 1000.
     *
     * [--batch=<number>]
     * : Transaction commit batch size. Default: 1000.
     *
     * [--label=<string>]
     * : Batch label for traceability (stored into meta `_aurora_seed_batch`). Default: current UTC timestamp.
     */
    public function __invoke( array $args, array $assoc_args ) : void {
        if ( ! class_exists( '\WooCommerce' ) ) {
            WP_CLI::error( 'WooCommerce must be active to seed products.' );
        }

        $count        = isset( $assoc_args['count'] ) ? max( 1, (int) $assoc_args['count'] ) : 50000;
        $progressStep = isset( $assoc_args['progress'] ) ? max( 1, (int) $assoc_args['progress'] ) : 1000;
        $batchSize    = isset( $assoc_args['batch'] ) ? max( 1, (int) $assoc_args['batch'] ) : 1000;
        $label        = $assoc_args['label'] ?? gmdate( 'Ymd-His' );
        $startIndex   = isset( $assoc_args['start-index'] ) ? max( 0, (int) $assoc_args['start-index'] ) : null;

        $termTaxId = $this->getSimpleProductTerm();
        $sequenceBase = $startIndex ?? $this->detectSequenceBase();

        $siteUrl = (string) get_option( 'siteurl', '' );
        if ( '' === $siteUrl ) {
            WP_CLI::error( 'Option siteurl is empty, cannot craft GUIDs.' );
        }

        $nowLocal = current_time( 'mysql' );
        $nowGmt   = current_time( 'mysql', true );
        $guidMarker = 'aurora-seed-guid-' . uniqid( '', true );

        $metaTable     = $this->db->postmeta;
        $termRelTable  = $this->db->term_relationships;
        $termTaxTable  = $this->db->term_taxonomy;
        $postsTable    = $this->db->posts;
        $lookupTable   = $this->db->prefix . 'wc_product_meta_lookup';

        $metaBuffer   = [];
        $termBuffer   = [];
        $lookupBuffer = [];
        $metaLimit    = 1000;
        $termLimit    = 1000;
        $lookupLimit  = 500;

        $this->db->query( 'SET autocommit = 0' );
        $this->db->query( 'START TRANSACTION' );

        $inserted    = 0;
        $firstPostId = null;
        $lastPostId  = null;
        $startTime   = microtime( true );

        WP_CLI::log( sprintf( 'Seeding %d products starting from #%d (label %s, batch %d)', $count, $sequenceBase + 1, $label, $batchSize ) );

        try {
            for ( $i = 0; $i < $count; $i++ ) {
                $number   = $sequenceBase + $i + 1;
                $price    = round( 10 + ( $number % 91 ) + 0.99, 2 );
                $qty      = 5 + ( $number % 46 );
                $title    = sprintf( 'Seed Product #%05d', $number );
                $slug     = sanitize_title( $title );
                $desc     = sprintf( 'Benchmark seed %s product #%05d generated by Aurora.', $label, $number );
                $sku      = sprintf( 'SEED-%s-%05d', strtoupper( substr( $label, 0, 6 ) ), $number );
                $priceStr = number_format( $price, 2, '.', '' );

                $result = $this->db->insert(
                    $postsTable,
                    [
                        'post_author'           => 1,
                        'post_date'             => $nowLocal,
                        'post_date_gmt'         => $nowGmt,
                        'post_content'          => $desc,
                        'post_title'            => $title,
                        'post_excerpt'          => '',
                        'post_status'           => 'publish',
                        'comment_status'        => 'closed',
                        'ping_status'           => 'closed',
                        'post_password'         => '',
                        'post_name'             => $slug,
                        'to_ping'               => '',
                        'pinged'                => '',
                        'post_modified'         => $nowLocal,
                        'post_modified_gmt'     => $nowGmt,
                        'post_content_filtered' => '',
                        'post_parent'           => 0,
                        'guid'                  => $guidMarker,
                        'menu_order'            => 0,
                        'post_type'             => 'product',
                        'post_mime_type'        => '',
                        'comment_count'         => 0,
                    ],
                    [
                        '%d', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s',
                        '%s', '%s', '%s', '%s', '%s', '%s', '%d', '%s', '%d', '%s', '%s', '%d',
                    ]
                );

                if ( false === $result ) {
                    throw new \RuntimeException( 'Failed inserting post: ' . $this->db->last_error );
                }

                $postId = (int) $this->db->insert_id;
                $firstPostId = $firstPostId ?? $postId;
                $lastPostId  = $postId;

                $this->enqueueMeta( $metaBuffer, $metaLimit, $metaTable, $postId, '_regular_price', $priceStr );
                $this->enqueueMeta( $metaBuffer, $metaLimit, $metaTable, $postId, '_price', $priceStr );
                $this->enqueueMeta( $metaBuffer, $metaLimit, $metaTable, $postId, '_stock', (string) $qty );
                $this->enqueueMeta( $metaBuffer, $metaLimit, $metaTable, $postId, '_manage_stock', 'yes' );
                $this->enqueueMeta( $metaBuffer, $metaLimit, $metaTable, $postId, '_stock_status', $qty > 0 ? 'instock' : 'outofstock' );
                $this->enqueueMeta( $metaBuffer, $metaLimit, $metaTable, $postId, '_sku', $sku );
                $this->enqueueMeta( $metaBuffer, $metaLimit, $metaTable, $postId, '_aurora_seed_batch', $label );

                $this->enqueueTerm( $termBuffer, $termLimit, $termRelTable, $postId, $termTaxId );
                $this->enqueueLookup( $lookupBuffer, $lookupLimit, $lookupTable, $postId, $sku, $price, $qty );

                $inserted++;

                if ( 0 === ( $inserted % $batchSize ) ) {
                    $this->commitCycle( $metaBuffer, $termBuffer, $lookupBuffer, $metaTable, $termRelTable, $lookupTable );
                }

                if ( 0 === ( $inserted % $progressStep ) ) {
                    $elapsed = microtime( true ) - $startTime;
                    $rate    = $elapsed > 0 ? $inserted / $elapsed : 0;
                    WP_CLI::log( sprintf( '[%s] %d/%d (%.1f%%) — %.1f products/s', current_time( 'H:i:s', true ), $inserted, $count, ( $inserted / $count ) * 100, $rate ) );
                }
            }

            $this->flushBuffers( $metaBuffer, $termBuffer, $lookupBuffer, $metaTable, $termRelTable, $lookupTable );
            $this->updateGuids( $postsTable, $guidMarker, $siteUrl );

            if ( false === $this->db->query( 'COMMIT' ) ) {
                throw new \RuntimeException( 'Final commit failed: ' . $this->db->last_error );
            }

            $termCountUpdated = $this->db->query(
                $this->db->prepare(
                    "UPDATE {$termTaxTable} SET count = count + %d WHERE term_taxonomy_id = %d",
                    $inserted,
                    $termTaxId
                )
            );
            if ( false === $termCountUpdated ) {
                throw new \RuntimeException( 'Failed updating product_type term count: ' . $this->db->last_error );
            }

            if ( false === $this->db->query( 'COMMIT' ) ) {
                throw new \RuntimeException( 'Final term count commit failed: ' . $this->db->last_error );
            }
        } catch ( \Throwable $throwable ) {
            $this->db->query( 'ROLLBACK' );
            WP_CLI::error( $throwable->getMessage() );
        } finally {
            $this->db->query( 'SET autocommit = 1' );
        }

        $elapsed = microtime( true ) - $startTime;
        $rate    = $elapsed > 0 ? $inserted / $elapsed : 0;

        WP_CLI::success( sprintf( 'Created %d products (IDs %d → %d) in %.2f seconds — %.1f products/s. Batch=%s', $inserted, $firstPostId ?? 0, $lastPostId ?? 0, $elapsed, $rate, $label ) );
    }

    private function detectSequenceBase() : int {
        $maxSeed = (int) $this->db->get_var(
            "SELECT MAX(CAST(SUBSTRING_INDEX(meta_value, '-', -1) AS UNSIGNED)) FROM {$this->db->postmeta} WHERE meta_key = '_sku' AND meta_value LIKE 'SEED-%-%'"
        );
        return $maxSeed;
    }

    private function getSimpleProductTerm() : int {
        $termTaxId = (int) $this->db->get_var(
            $this->db->prepare(
                "SELECT tt.term_taxonomy_id FROM {$this->db->terms} t INNER JOIN {$this->db->term_taxonomy} tt ON tt.term_id = t.term_id WHERE t.slug = %s AND tt.taxonomy = %s LIMIT 1",
                'simple',
                'product_type'
            )
        );
        if ( $termTaxId <= 0 ) {
            WP_CLI::error( 'Unable to locate product_type=simple term_taxonomy entry.' );
        }
        return $termTaxId;
    }

    private function enqueueMeta( array &$buffer, int $limit, string $table, int $postId, string $key, string $value ) : void {
        $buffer[] = $this->db->prepare( '( %d, %s, %s )', $postId, $key, $value );
        if ( count( $buffer ) >= $limit ) {
            $this->flushBuffer( $buffer, $table, 'post_id, meta_key, meta_value' );
        }
    }

    private function enqueueTerm( array &$buffer, int $limit, string $table, int $postId, int $termTaxId ) : void {
        $buffer[] = $this->db->prepare( '( %d, %d, 0 )', $postId, $termTaxId );
        if ( count( $buffer ) >= $limit ) {
            $this->flushBuffer( $buffer, $table, 'object_id, term_taxonomy_id, term_order' );
        }
    }

    private function enqueueLookup( array &$buffer, int $limit, string $table, int $postId, string $sku, float $price, int $qty ) : void {
        $buffer[] = $this->db->prepare(
            '( %d, %s, %s, 0, 0, %f, %f, 0, %d, %s, 0, 0, 0, %s, %s )',
            $postId,
            $sku,
            '',
            $price,
            $price,
            $qty,
            $qty > 0 ? 'instock' : 'outofstock',
            'taxable',
            ''
        );
        if ( count( $buffer ) >= $limit ) {
            $this->flushBuffer( $buffer, $table, '`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`' );
        }
    }

    private function commitCycle( array &$metaBuffer, array &$termBuffer, array &$lookupBuffer, string $metaTable, string $termTable, string $lookupTable ) : void {
        $this->flushBuffers( $metaBuffer, $termBuffer, $lookupBuffer, $metaTable, $termTable, $lookupTable );
        if ( false === $this->db->query( 'COMMIT' ) ) {
            throw new \RuntimeException( 'Commit failed: ' . $this->db->last_error );
        }
        if ( false === $this->db->query( 'START TRANSACTION' ) ) {
            throw new \RuntimeException( 'Unable to restart transaction: ' . $this->db->last_error );
        }
    }

    private function flushBuffers( array &$metaBuffer, array &$termBuffer, array &$lookupBuffer, string $metaTable, string $termTable, string $lookupTable ) : void {
        $this->flushBuffer( $metaBuffer, $metaTable, 'post_id, meta_key, meta_value' );
        $this->flushBuffer( $termBuffer, $termTable, 'object_id, term_taxonomy_id, term_order' );
        $this->flushBuffer( $lookupBuffer, $lookupTable, '`product_id`, `sku`, `global_unique_id`, `virtual`, `downloadable`, `min_price`, `max_price`, `onsale`, `stock_quantity`, `stock_status`, `rating_count`, `average_rating`, `total_sales`, `tax_status`, `tax_class`' );
    }

    private function flushBuffer( array &$buffer, string $table, string $columns ) : void {
        if ( empty( $buffer ) ) {
            return;
        }
        $sql = "INSERT INTO {$table} ({$columns}) VALUES " . implode( ',', $buffer );
        $result = $this->db->query( $sql );
        if ( false === $result ) {
            throw new \RuntimeException( 'Failed writing batch: ' . $this->db->last_error );
        }
        $buffer = [];
    }

    private function updateGuids( string $postsTable, string $guidMarker, string $siteUrl ) : void {
        $result = $this->db->query(
            $this->db->prepare(
                "UPDATE {$postsTable} SET guid = CONCAT(%s, '/?post_type=product&p=', ID) WHERE guid = %s",
                $siteUrl,
                $guidMarker
            )
        );
        if ( false === $result ) {
            throw new \RuntimeException( 'Failed updating GUIDs: ' . $this->db->last_error );
        }
    }
}
